/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:6a0ca329-ff5a-4939-b4da-ffdcb3ab77af',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_HQDEIqLNS',
    aws_user_pools_web_client_id: '1utu4g6aqgotbkp625pvldl9b4',
    oauth: {}
};


export default awsmobile;
